import { sva } from '@styled/css';

export const settingsPanelRecipe = sva({
  slots: [
    'root',
    'block',
    'heading',
    'row',
    'text',
    'note',
    'switch',
    'agent',
    'chip',
    'state',
    'path',
  ],
  base: {
    root: { display: 'grid', gap: '5', alignContent: 'start' },
    block: { display: 'grid' },
    heading: {
      margin: 0,
      marginBottom: '1',
      textStyle: 'tag',
      color: 'textMuted',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
    row: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) auto',
      alignItems: 'center',
      gap: '3',
      paddingBlock: '2',
      borderBottom: '1px solid {colors.edge}',
    },
    text: { textStyle: 'body', minWidth: 0 },
    note: { display: 'block', textStyle: 'caption', color: 'textMuted' },
    switch: {
      position: 'relative',
      width: '38px',
      height: '20px',
      padding: 0,
      background: 'raised',
      border: '2px solid {colors.edge}',
      cursor: 'pointer',
      _after: {
        content: '""',
        position: 'absolute',
        top: '2px',
        left: '2px',
        width: '12px',
        height: '12px',
        background: 'inkDim',
      },
      _focusVisible: { outline: '2px solid {colors.ink}', outlineOffset: '2px' },
      '&[aria-checked=true]': { borderColor: 'coin' },
      '&[aria-checked=true]::after': { left: '20px', background: 'coin' },
      _disabled: { cursor: 'progress', opacity: 0.6 },
    },
    agent: {
      display: 'grid',
      gridTemplateColumns: '10px minmax(0, 1fr) auto',
      alignItems: 'center',
      gap: '2',
      paddingBlock: '1.5',
      borderBottom: '1px solid {colors.edge}',
    },
    chip: { width: '10px', height: '10px' },
    state: { textStyle: 'caption', color: 'textMuted' },
    path: { display: 'block', textStyle: 'caption', color: 'textMuted', overflowWrap: 'anywhere' },
  },
  variants: {
    found: {
      true: { state: { color: 'text' } },
      false: { agent: { opacity: 0.6 } },
    },
  },
});
